Homework 1. Task simple_1. Мищенко Станислав Алексеевич
mi-sts/spbu_kotlin_homeworks pull request #1
Opened 2021-02-26 14:11 UTC by mi-sts

2021-03-01 15:13 UTC, nbirillo requested changes

2021-03-01 15:13 UTC, nbirillo commented on src/main/kotlin/libraries/Input.kt
> +class Input private constructor() {
А зачем тебе класс такой? Ну сделай просто функцию без класса (так делают в котлине часто для util функций) или в крайнем случае `object` и внутри уже функцию

2021-03-01 15:13 UTC, nbirillo commented on src/main/kotlin/libraries/Input.kt
> +        fun getNaturalNumber(enableFirstMessage: Boolean = true): Int {
Может логичнее тогда сделать переменную, которая позволяет показывать\не показывать весь текст? а то так как-то странно выглядит

2021-03-01 15:13 UTC, nbirillo commented on src/main/kotlin/libraries/Input.kt
> +            while (number <= 0) {
У тебя конечно название говорит про натуральные числа, но конкретно для факториала - его от нуля можно посчитать нормально

2021-03-01 15:13 UTC, nbirillo commented on src/main/kotlin/homework_1/task_simple_1_recursive.kt
> +private fun printResult(factorial: Long) = println("Found the factorial: $factorial")
Ну если ты решил разделить по разным файлам функции факториала, а эта общая, то ее надо в какой-нибудь factorialUtil вынести. Не нужно писать одинаковый код дважды

2021-03-02 17:34 UTC, nbirillo requested changes
Небольшие комментарии остались

2021-03-02 17:34 UTC, nbirillo commented on src/main/kotlin/libraries/Input.kt
> +    fun getNaturalNumber(preInputMessage: String = ""): Long {
Ты кажется не используешь эту функцию в этой задаче

2021-03-02 17:34 UTC, nbirillo commented on src/main/kotlin/libraries/Input.kt
> +    fun getNonNegativeNumber(preInputMessage: String = ""): Long {
А еще у тебя эти функции отличаются лишь сообщением об ошибке и дефолтным значением и знак в одном месте. Кажется их можно как-то объединить

2021-03-02 17:37 UTC, mi-sts commented on src/main/kotlin/libraries/Input.kt
> +    fun getNaturalNumber(preInputMessage: String = ""): Long {
Думал оставить на будущее

2021-03-04 12:11 UTC, nbirillo requested changes

2021-03-04 12:11 UTC, nbirillo commented on src/main/kotlin/homework_1/task_simple_1_iterative.kt
> +fun main() {
![image](https://user-images.githubusercontent.com/8993915/109962064-d1988000-7cfb-11eb-93bb-102f3c2df7e2.png)

2021-03-04 12:11 UTC, nbirillo commented on src/main/kotlin/homework_1/task_simple_1_recursive.kt
> +fun main() {
![image](https://user-images.githubusercontent.com/8993915/109962115-dfe69c00-7cfb-11eb-814e-1d9eafe640d4.png)

2021-03-05 07:56 UTC, nbirillo approved these changes
Зачтено

2021-03-05 07:56 UTC, merged