Homework 3. Task hard. Мищенко Станислав Алексеевич
mi-sts/spbu_kotlin_homeworks pull request #11
Opened 2021-04-02 21:01 UTC by mi-sts

2021-04-03 15:09 UTC, cupertank requested changes

2021-04-03 15:09 UTC, cupertank commented on build.gradle.kts
> +    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
Это должно быть testImplementation
Почисти билдфайл от повторений и синхронизируй версии

2021-04-03 15:09 UTC, cupertank commented on build.gradle.kts
> +    }
Зачем ты скопировал это с KInference, я же вам написал что нужно забрать....
Ты же даже не понимаешь что это значит....

2021-04-03 15:09 UTC, cupertank commented on build.gradle.kts
> +    }
Причем то что нужно ты так и не добавил.....

2021-04-03 15:09 UTC, cupertank commented on build.gradle.kts
> +    }
Я просил добавить
```
testLogging {
        events(
            TestLogEvent.STANDARD_ERROR,
            TestLogEvent.STARTED,
            TestLogEvent.PASSED,
            TestLogEvent.FAILED,
            TestLogEvent.SKIPPED
        )
    }
```
Добавь пожалуйста)

2021-04-03 15:09 UTC, cupertank commented on build.gradle.kts
> +}
Это конечно клево, что ты умеешь в делегаты, но у тебя это всё сделано вот здесь
```
tasks.withType<KotlinCompile>() {
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs = listOf("-Werror")
    }
}
```

2021-04-03 15:09 UTC, cupertank commented on config/detekt/detekt.yml
> +    packagePattern: '[a-z]+(_[A-Za-z0-9]+)*(\.[a-z](_[A-Za-z0-9]+)*[_A-Za-z0-9]*)*'
Зачем....?

2021-04-03 15:09 UTC, cupertank commented on src/main/kotlin/util/test_generator/TestDataParser.kt
> +}
Перенеси это в companion object у TestData

2021-04-03 15:09 UTC, cupertank commented on src/main/kotlin/util/test_generator/TestGenerator.kt
> +}
Объедени это в какой-нибудь класс, просто оно как-то валяется не круто

2021-04-03 15:09 UTC, cupertank commented on src/main/kotlin/util/test_generator/TestGenerator.kt
> +fun saveTestFile(fileSpec: FileSpec, directoryPath: String) = fileSpec.writeTo(File(directoryPath))
Это тоже к тому же классу

2021-04-03 15:09 UTC, cupertank commented on src/main/kotlin/util/test_generator/TestGenerator.kt
> +data class GenerationParameters(val dataFilePath: String, val directoryPath: String, val generatedFileName: String)
а зачем заводить целый датакласс ради трех переменных функции

2021-04-03 15:09 UTC, cupertank commented on src/test/kotlin/homework_3/CreateTestBlankTest.kt
> +package homework_3import util.test_generator.GenerationParametersimport util.test_generator.generateTestBlankimport org.junit.jupiter.api.Assertions.assertEqualsimport org.junit.jupiter.api.io.T
Не знаю что тут произошло, почини пожалуйста...

2021-04-03 15:09 UTC, cupertank commented on src/test/kotlin/homework_3/CreateTestBlankTest.kt
> +package homework_3import util.test_generator.GenerationParametersimport util.test_generator.generateTestBlankimport org.junit.jupiter.api.Assertions.assertEqualsimport org.junit.jupiter.api.io.T
Я не знаю что здесь, но в следующий раз я посмотрю только этот файл потому что сейчас он сломан

2021-04-03 16:20 UTC, mi-sts commented on config/detekt/detekt.yml
> +    packagePattern: '[a-z]+(_[A-Za-z0-9]+)*(\.[a-z](_[A-Za-z0-9]+)*[_A-Za-z0-9]*)*'
Это мы в первой домашке кастомизировали конфиг, чтобы детект не ругался на пакеты с нижним подчёркиванием в имени(вроде homework_1), но на пакет с именем test_generator он внезапно начал ругаться)

2021-04-04 13:17 UTC, cupertank approved these changes

2021-04-04 13:17 UTC, merged