Homework 5. Task 1. Мищенко Станислав Алексеевич
mi-sts/spbu_kotlin_homeworks pull request #14
Opened 2021-04-14 08:31 UTC by mi-sts

2021-04-14 19:17 UTC, SpirinEgor requested changes

2021-04-14 19:17 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/AriphmeticTreeElements.kt
> +abstract class ArithmeticElement(protected val height: Int) {
Абстрактный класс, у которого все методы абстрактные -- это интерфейс.
С ним код будет чуть чище выглядеть, да и понятнее.

2021-04-14 19:17 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/AriphmeticTreeElements.kt
> +abstract class Operation(
И тут аналогично, лучше интерфейсом назвать

2021-04-14 19:17 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/AriphmeticTreeElements.kt
> +abstract class Operation(
Или можно оставить abstract и определить метод getWritten. Для этого надо будет добавить абстрактное поле `sign`

2021-04-14 19:17 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/AriphmeticTreeElements.kt
> +    abstract fun getWritten(): String
Метод, который делает строковое представление, называется `toString`. Он есть у каждого объекта. Лучше его переопределять, тогда, например, можно спокойно вызывать принт от объекта и он сам все сконвертит.

2021-04-14 19:17 UTC, SpirinEgor commented on src/main/kotlin/homework_5/task_1.kt
> +    arithmeticTree ?: return
Ну, наверное, тут лучше вывести, что дерева не существует, что какая-то ошибка...

2021-04-14 19:17 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/ArithmeticTree.kt
> +    private const val FIRST_EXPRESSION_MEMBER_START_INDEX = 3
А зачем?)
Есть такая [штука](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition), детская задача с типо интерпрайз кодом.
И в ней сделали список [констант](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/blob/uinverse/src/main/java/com/seriouscompany/business/java/fizzbuzz/packagenamingpackage/impl/Constants.java), там даже отдельная константа для цикла!

Понятно, что это крайний случай, который высмеивает практики. Не надо ему уподобляться и заводить лишние константы.

2021-04-14 19:17 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/ArithmeticTree.kt
> +        val (operation, firstExpression, secondExpression) = getExpressionMembers(expression)
А если expression уже число, то как он разложит на 3 части?

2021-04-14 19:17 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/ArithmeticTree.kt
> +            else createArithmeticBranch(firstExpression, height + 1)!!
!!!

2021-04-14 19:17 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/ArithmeticTree.kt
> +        return listOf(operation, firstExpression, secondExpression)
Мне не очень нравится, что тут создаётся лист. Лучше датакласс использовать. Или вообще сразу вершину создавать.

2021-04-16 16:01 UTC, mi-sts commented on src/main/kotlin/util/arithmetic_parser/ArithmeticTree.kt
> +    private const val FIRST_EXPRESSION_MEMBER_START_INDEX = 3
@SpirinEgor Но в таком случае detekt выдаст MagicNumber и вроде бы это единственный способ это обойти

2021-04-16 17:26 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/ArithmeticTree.kt
> +    private const val FIRST_EXPRESSION_MEMBER_START_INDEX = 3
В таком случае лучше в конфиг добавить исключения на эти числа. Вроде 1 и так игнорируется, надо 3 только добавить

2021-04-16 17:29 UTC, SpirinEgor reviewed
Добавь числа в допустимые для детекта и убери эти штуки с константами. В остальном выглядит хорошо.

2021-04-16 17:29 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/AriphmeticTreeElements.kt
> +    override fun toString(): String
Её в целом необязательно указывать

2021-04-19 10:44 UTC, SpirinEgor approved these changes

2021-04-19 10:44 UTC, SpirinEgor commented on src/main/kotlin/util/arithmetic_parser/ArithmeticTree.kt
> +@Suppress("MagicNumber")
Надо было исключение в конфиг добавить, а не отключить всю проверку правила...

2021-04-19 10:44 UTC, merged