Homework 6. Task 1. Мищенко Станислав Алексеевич
mi-sts/spbu_kotlin_homeworks pull request #17
Opened 2021-04-17 16:44 UTC by mi-sts

2021-04-20 19:48 UTC, elena-lyulina requested changes

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +    private fun clearStatisticsChart() = statisticsSeries?.data?.clear()
в классе идут сначала свойства, потом методы https://kotlinlang.org/docs/coding-conventions.html#class-layout

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +    private val threadsSliderMaxValue = 1000
это можно сделать константами

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/merge_sort_statistics.kt
> +package homework_6
Имена файлов должны быть CamelCase https://kotlinlang.org/docs/coding-conventions.html#source-file-names

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +    private var dependentVariableSlider: Slider? = null
ui компоненты, которые будут потом инициализированы, можно сделать lateinit, тогда их можно сделать non-nullable

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +        }
лучше сделать enum class Mode, это лучше, чем просто булеан isElementsMode, так как:
1. можно их легко перебирать при помощи when, а не в if
2. все время понятно, какой сейчас mode, а с булеан не очень, приходится помнить, а что за второй mode, который не ElementMode
3. если появится третий мод (а он скорее всего появится, когда будут корутины), будет легче его начать поддерживать

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +        val approximationStepsNumber = 3
вот это тоже лучше вынести в константу

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +            if (!isElementsMode) {
ну вот и опять аргумент в пользу enum class -- ты то !isElementsMode, то isElementsMode, так очень легко запутаться

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +@file:Suppress("MagicNumber")
очень классные графики, понравились слайдеры, спасибо! единственное, что мб в начале стоит один из модов включить, чтобы сразу нужные оси и подписи рисовались, а то у тебя надписи соответствуют ElementMode изначально, а он не выбран
![image](https://user-images.githubusercontent.com/24303332/115444013-ad95ed00-a21c-11eb-8459-6977f77a2d6f.png)

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/util/sorts/MergeSort.kt
> +package util.sorts
а почему это в утиле лежит? это же напрямую к 6й домашке относится

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/merge_sort_statistics.kt
> +            generalTimeData[i] = generalTimeData[i] ?: 0 + elapsedTime
если ты имел в виду "увеличить текущее значение (или ноль, если его еще нет) на elapsedTime", то тебе нужны скобки:
(generalTimeData[i] ?: 0) + elapsedTime

сейчас это работает вот так: generalTimeData[i] ?: (0 + elapsedTime)

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/merge_sort_statistics.kt
> +            generalTimeData[i] = generalTimeData[i] ?: 0 + elapsedTime
а еще лучше вместо (generalTimeData[i] ?: 0) использовать getOrPut

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/merge_sort_statistics.kt
> +    if (numberOfElements <= 0) throw IllegalArgumentException("The number of sorting elements should be positive!")
можно использовать require, делает примерно то же самое, выглядит чуть красивее

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/merge_sort_statistics.kt
> +fun getSortStaticsDependingOnElementsNumber(
у тебя эти две функции практически одинаковы, попробуй сделать одну. отличающиеся вещи типа получения рандомного списка или запуска сортировки можно вынести в параметры (они могут быть функциями)

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/util/sorts/MergeSort.kt
> +    fun <T : Comparable<T>> merge(leftList: List<T>?, rightList: List<T>?): List<T> {
давай это тоже будет многопоточным

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/util/sorts/MultithreadedMergeSort.kt
> +        return mainRunnable.getSorted()
лучше не называть что-либо main thread, main thread это очень конкретная штука

2021-04-20 19:48 UTC, elena-lyulina commented on src/main/kotlin/util/sorts/MultithreadedMergeSort.kt
> +                NullPointerException("The sorted list is null!")
лучше использовать require

2021-04-20 19:48 UTC, elena-lyulina commented on src/test/kotlin/util/sorts/MergeSortTest.kt
> +package util.sorts
хочется тесты на многопоточную сортировку тоже

2021-05-03 11:36 UTC, elena-lyulina requested changes
уже близко!

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +                statisticsSeries.chart?.xAxis?.label = "Elements"
у тебя же есть переменная elementsLabel, почему ты ее не используешь здесь? и threadsLabel чуть ниже? ну и раз такое дело, можно "Nanoseconds" тоже вынести в свойства класса

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +                statisticsSeries.chart?.yAxis?.label = "Nanoseconds"
вот эта строчка одинаковая во всех модах, ее можно вынести и сделать после when

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +                statisticsSeries.chart?.xAxis?.label = "Elements"
еще лучше cделать поле у enum'а, например, так:
```
    enum class Mode(val modeName: String) {
        ELEMENTS_MODE("Elements"),
        THREADS_MODE("Threads")
    }
```

и тогда можно будет просто обращаться currentMode.modeName, без необходимости проверять конкретные варианты

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +                statisticsSeries.chart?.xAxis?.label = "Elements"
ну и соответственно в других местах так же или ELEMENTS_MODE.modeName, если тебе надо конкретную label получить

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +                        onModeButtonPressed(Mode.ELEMENTS_MODE)
вот эта строчка тоже повторяется, ты по сути можешь просто сделать onModeButtonPressed(currentMode)

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +        if (isModeChosen && currentMode == modeOfButton) return
тебе все еще нужен isModeChosen?

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/MergeSortStatisticsApp.kt
> +                statisticsSeries.chart?.yAxis?.label = "Nanoseconds"
и в других местах тоже есть такие случаи, проверь, что ты нигде не пишешь лишний код

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +                rightThread.run()
Надо вызывать start, а не run, run просто запускает Runnable не создавая новый поток

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +                rightThread.run()
и можешь посмотреть, как графики меняются, когда ты правильно потоки запускать начнешь

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +            val availableThreads = numberOfAvailableThreads - 1
а почему так?

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +                    (numberOfAvailableThreads * MERGE_THREADS_COEFFICIENT).toInt())
зачем ты на коэффициент какой-то умножаешь? откуда он вообще?

2021-05-03 11:36 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +                    rightThread.run()
и тут

2021-05-03 11:36 UTC, elena-lyulina commented on src/test/kotlin/homework_6/task_1/sorts/MergeSortTest.kt
> +        assertEquals(mergedList, multithreadedMerge(firstList, secondList, 100))
давай количество потоков тоже будет параметром

2021-05-03 11:36 UTC, elena-lyulina commented on src/test/kotlin/homework_6/task_1/sorts/MergeSortTest.kt
> +        assertEquals(list.sorted(), list.multithreadedMergeSorted(100))
и тут

2021-05-04 11:38 UTC, mi-sts commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +            val availableThreads = numberOfAvailableThreads - 1
@elena-lyulina до этого число потоков было равно числу "листьев" в графе рекурсивного запуска потоков, т.е. я не учитывал те потоки, которые ничего не делали, а просто рекурсивно запускали ещё два потока. Здесь я исправил это

2021-05-04 11:42 UTC, mi-sts commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +                    (numberOfAvailableThreads * MERGE_THREADS_COEFFICIENT).toInt())
@elena-lyulina реализация многопоточного мёрджа так же имеет ограничение по числу создаваемых потоков и я понял, что лучше всего выделять для такого мёрджа максимальное число потоков равное текущему доступному количеству потоков для текущего шага сортировки, умноженному на этот коэффициент

2021-05-04 18:47 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +            val availableThreads = numberOfAvailableThreads - 1
окей, пусть будет так)

2021-05-04 18:47 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +            val availableThreads = numberOfAvailableThreads - 1
но добавь тогда соответствующий комментарий, а то это не очень очевидно

2021-05-04 18:49 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1/sorts/MultithreadedMergeSort.kt
> +                    (numberOfAvailableThreads * MERGE_THREADS_COEFFICIENT).toInt())
да, но почему бы не ограничивать многопоточный мёрдж просто количеством доступных потоков? зачем брать только одну десятую от них? все потоки, которые ты в этом mergeSort вызывал до этого, уже закончили свою работу (ты у них вызвал join), значит, ты можешь опять использовать то же количество потоков

2021-05-04 18:50 UTC, elena-lyulina requested changes
уже близко!

2021-05-04 18:50 UTC, elena-lyulina commented on src/test/kotlin/homework_6/task_1/sorts/MergeSortTest.kt
> +            assertEquals(mergedList, multithreadedMerge(firstList, secondList, i))
о нет, только не assert в цикле, как же ты будешь понимать, что именно упало, если что-то упадет? давай-ка делать параметризованные тесты, они специально для этого нужны, количество потоков тоже будет параметром

2021-05-04 18:50 UTC, elena-lyulina commented on src/test/kotlin/homework_6/task_1/sorts/MergeSortTest.kt
> +        }
и тут цикл :(

2021-05-13 16:23 UTC, elena-lyulina requested changes
прям совсем близко

2021-05-13 16:23 UTC, elena-lyulina commented on src/test/kotlin/homework_6/task_1/sorts/MergeSortTest.kt
> +                Arguments.of(mutableListOf(-4, 5, 12, 0, 89, 44, 13, 7, 6, 3, 7), it)
у тебя же уже есть numbersList, ты же можешь по нему пройтии и добавить it каждый из них, зачем повторять?
ну и про sortedListWithThreads так же

2021-05-27 21:06 UTC, elena-lyulina requested changes
еще чуть-чуть

2021-05-27 21:06 UTC, elena-lyulina commented on src/test/kotlin/homework_6/task_1/sorts/MergeSortTest.kt
> +}
это точно тут должно быть?

2021-05-31 19:26 UTC, elena-lyulina approved these changes
поправь, пожалуйста, конфликты, и я солью

2021-05-31 20:19 UTC, merged