Homework 7. Task 2. Мищенко Станислав Алексеевич
mi-sts/spbu_kotlin_homeworks pull request #19
Opened 2021-04-30 20:55 UTC by mi-sts

2021-05-13 15:51 UTC, elena-lyulina requested changes

2021-05-13 15:51 UTC, elena-lyulina commented on src/main/kotlin/homework_7/task_1/Matrix.kt
> +    }
а в чем смысл такого?

2021-05-13 15:51 UTC, elena-lyulina commented on src/main/kotlin/homework_7/task_1/Matrix.kt
> +            areMatrixArraysEqual
это можно сделать одной строчкой, если использовать `all`
и еще полезно добавить в начало проверку, что other это тоже матрица

2021-05-13 15:51 UTC, elena-lyulina commented on src/test/kotlin/homework_7/task_1/MatrixTest.kt
> +        fun multiplicationMatrices(): List<Arguments> = listOf(
добавь еще, пожалуйста, тесты с матрицами большего размера, а так же с отрицательными числами и нулями

2021-05-13 15:51 UTC, elena-lyulina commented on src/main/kotlin/homework_7/task_1/Matrix.kt
> +    private val width = matrixArray[0].size
а что с порядком элементов в классе? давай ты перечитаешь стайл гайды)

2021-05-13 15:51 UTC, elena-lyulina commented on src/main/kotlin/homework_7/task_1/Matrix.kt
> +            IllegalArgumentException("The matrix size cannot be zero!") }
а что будет, если у тебя дабл массивы разного размера?

2021-05-14 21:30 UTC, mi-sts commented on src/main/kotlin/homework_7/task_1/Matrix.kt
> +    }
@elena-lyulina detekt обязательно требует переопределения hashCode() при переопределении equals()

2021-05-14 21:32 UTC, mi-sts commented on src/main/kotlin/homework_7/task_1/Matrix.kt
> +            IllegalArgumentException("The matrix size cannot be zero!") }
@elena-lyulina вроде бы всё хорошо должно быть, у меня реализация подходит для умножения не только квадратных матриц

2021-05-27 21:12 UTC, elena-lyulina requested changes

2021-05-27 21:12 UTC, elena-lyulina commented on src/main/kotlin/homework_7/task_1/Matrix.kt
> +            IllegalArgumentException("The matrix size cannot be zero!") }
я имела в виду, если это будет не матрица, а, например, такая штука:
```
[[1, 2], [2, 2, 2], [1]]
```

2021-05-27 21:12 UTC, elena-lyulina commented on src/main/kotlin/homework_7/task_1/Matrix.kt
> +            IllegalArgumentException("The matrix size cannot be zero!") }
еще кстати в require можно просто передавать сообщение, и он сам кинет IllegalArgumentException

2021-05-31 19:23 UTC, elena-lyulina approved these changes

2021-05-31 19:23 UTC, merged