Change standart detekt config. Мищенко Станислав Алексеевич
mi-sts/spbu_kotlin_homeworks pull request #2
Opened 2021-02-26 18:54 UTC by mi-sts

2021-02-26 20:54 UTC, mi-sts commented
Кастомный конфиг почему-то никак не меняет ситуацию с проверкой именования пакетов во время проверки.

2021-02-27 11:41 UTC, mi-sts commented
Теперь должно работать нормально.

2021-03-01 10:43 UTC, nbirillo requested changes
Сделай замену только именования пакетов, а остальное используй дефолтное. Не надо весь конфиг сюда тащить

2021-03-01 12:01 UTC, nbirillo approved these changes

2021-03-01 12:01 UTC, merged