Homework 1. Task simple_2. Мищенко Станислав Алексеевич
mi-sts/spbu_kotlin_homeworks pull request #3
Opened 2021-02-27 17:29 UTC by mi-sts

2021-03-01 12:09 UTC, nbirillo commented
Тести почини и потом уже назначай на ревью))

2021-03-01 15:40 UTC, nbirillo requested changes

2021-03-01 15:40 UTC, nbirillo commented on src/main/kotlin/libraries/Input.kt
> +class Input private constructor() {
Тот же комментарий, что и в прошлом пр - зачем тебе тут класс?

2021-03-01 15:40 UTC, nbirillo commented on src/main/kotlin/homework_1/taks_simple_2.kt
> +        if (isOccur) occurrencesCount += 1
Ну это чисто Сишный код. Давай ты попробуешь использовать что-то из Котлина, что позволит работать со строками\коллекциями и писать код, похожий на Котлиновский

2021-03-02 17:40 UTC, nbirillo requested changes

2021-03-02 17:40 UTC, nbirillo commented on src/main/kotlin/homework_1/taks_simple_2.kt
> +    }
Это уже больше похоже на котлин, но `substring` копирует строку каждый раз, что плохо. Думай дальше :)

2021-03-02 17:40 UTC, nbirillo commented on src/main/kotlin/homework_1/taks_simple_2.kt
> +fun findSubstringCount(str: String, subStr: String): Int {
(чисто стилистически, но смотрится приятнее). Лучше сделать функцию-расширение для класса `String`, куда будет подаваться вторая строка, так читать понятнее обычно:
```
fun String. findSubstringCount(subStr: String): Int { ... }
```
и вызывать тогда в твоем случае
```
str. findSubstringCount(subStr) 
```
тут сразу интуитивно понятно, в какой строке какую искать и выглядит красиво. Но это уже смотри сам как тебе нравится больше, у тебя названия не string1, string2, так что в целом тоже понятно что происходит

2021-03-02 17:40 UTC, nbirillo commented on src/main/kotlin/homework_1/taks_simple_2.kt
> +}
Можно в одну строчку написать без {}, короткая функция же

2021-03-02 17:40 UTC, nbirillo commented on src/main/kotlin/homework_1/taks_simple_2.kt
> +    printResult(count)
Ну тут наверное тоже лучше заинлайнить и сделать так:
```
printResult(findSubstringCount(str, subStr))
```

2021-03-04 12:14 UTC, nbirillo requested changes

2021-03-04 12:14 UTC, nbirillo commented on src/main/kotlin/homework_1/taks_simple_2.kt
> +fun main() {
Сделай корректную обработку всех случаев с пустыми строчками - когда обе пустые; когда первая пустая, а вторая нет и когда вторая пустая, а первая нет. Сейчас у тебя не все обрабатывается верно и вылетают ошибки

2021-03-05 07:58 UTC, nbirillo requested changes

2021-03-05 07:58 UTC, nbirillo commented on src/main/kotlin/libraries/StringExtensions.kt
> +    if (subString.length == 0) return 0
Ну даже идея говорит сама, что лучше использовать `subString.isEmpty()`

2021-03-05 07:59 UTC, nbirillo commented on src/main/kotlin/libraries/StringExtensions.kt
> +    if (subString.length == 0) return 0
+ конфликты надо пофиксить

2021-03-05 08:05 UTC, mi-sts commented on src/main/kotlin/libraries/StringExtensions.kt
> +    if (subString.length == 0) return 0
@nbirillo я вот как раз после этого и написал subString.isEmpty(), на что идея мне зачеркнула isEmpty() и написала, что этот метод в будущих версиях может отсутствовать)

2021-03-05 08:09 UTC, mi-sts commented on src/main/kotlin/libraries/StringExtensions.kt
> +    if (subString.length == 0) return 0
![image](https://user-images.githubusercontent.com/66365072/110086298-3f4bb700-7da3-11eb-8f5f-4db8c590b98a.png)

2021-03-05 10:44 UTC, nbirillo commented on src/main/kotlin/libraries/StringExtensions.kt
> +    if (subString.length == 0) return 0
а какая у тебя версия идеи\котлина?

2021-03-05 11:11 UTC, nbirillo commented on src/main/kotlin/libraries/StringExtensions.kt
> +    if (subString.length == 0) return 0
возможно у тебя устаревшая версия - https://youtrack.jetbrains.com/issue/KT-42838

2021-03-05 11:11 UTC, nbirillo commented on src/main/kotlin/libraries/StringExtensions.kt
> +    if (subString.length == 0) return 0
(еще один повод не всегда слушать идею)

2021-03-05 15:02 UTC, nbirillo approved these changes
зачтено

2021-03-05 15:02 UTC, merged