Homework 1. Task oop. Мищенко Станислав Алексеевич
mi-sts/spbu_kotlin_homeworks pull request #4
Opened 2021-02-28 18:01 UTC by mi-sts

2021-03-01 15:59 UTC, nbirillo requested changes
Вообщем, переделай, пожалуйста, основные архитектурные вопросы, а уже после мы вернемся к более детальному ревью

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +class UserInterface private constructor() {
Все тот же комментарий из первого пр

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +        StartInsertion('1'), EndInsertion('2'), Movement('3'),
В Enum классах обычно используют капс - https://kotlinlang.org/docs/coding-conventions.html#property-names

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +        val OPTIONS_RANGE: IntRange = 1..6
У тебя вот тут такой range, значения-value отдельно хранятся в `UserOption`...Так не стоит делать

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +            var toIndex: Int
Делать переменные без инициализации плохо

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +        fun showActionsMessage() {
Ну это видимо лучше добавить в класс UserInterface

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +        }
Такие короткие функции (функций ниже тоже касается) лучше писать в одну строчку:
```
fun showIncorrectInputMessage() =  println("The input must be a number between 1 and 6!")
```

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +class UserInterface private constructor() {
Когда ты поменяешь его на object, расставь, пожалуйста везде модификаторы доступа нормально, скрой ненужные функции и тд. Сейчас тут творится хаос какой-то. Класс UserOption можно вынести из этого класса и просто оставить в этом же файле

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +                        number = Input.getNumber(false)
Вот это повторяется два раза, вероятно можно вынести в функцию

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +class StorageManager private constructor() {
А зачем тебе этот класс? Здравая идея сделать менеджер, в котором будет свой экземпляр стораджа и список значений текущих например. ну и возможно какие-то обертки с этими мессаджами твоими. Но в таком виде это бесполезно абсолютно. При этом у тебя класс и опять все обернуто в companion object. Вообщем либо удали его совсем, либо переделай на что-то похожее, о чем я тут написала

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/structures/PerfomedCommandStorage.kt
> +package structures
Очень странный выбор названия для пакета))

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/structures/PerfomedCommandStorage.kt
> +    val actionType: ActionType = actionType
Это можно сразу в конструкторе делать

2021-03-01 15:59 UTC, nbirillo commented on src/main/kotlin/structures/PerfomedCommandStorage.kt
> +package structures
Вообще вам рассказывали про наследование. Можно сделать какой-то общий класс или интерфейс Action для всех действий, отнаследоваться и сделать класс для каждого действия, в котором будут реализованы методы прямом и обратного применения, которые будут оперировать с коллекцией и добавлять или двигать элементы. Также вероятно вызывать будут функцию стораджа, которая позволяет добавить текущее действие в коллекцию. Отменять действия можно будет очень удобно внутри стораджа в undo, вызывая метод для обратного применения и неважно какого действия. После чего удаляя это действие из коллекции действий в сторадже

2021-03-01 16:11 UTC, mi-sts commented on src/main/kotlin/homework_1/task_oop.kt
> +        val OPTIONS_RANGE: IntRange = 1..6
Я вынес его в отдельную переменную, потому что detekt писал на range в условии MagicNumber и не совсем понятно как это правильно нужно написать 
![image](https://user-images.githubusercontent.com/66365072/109524627-ceb24b00-7ac1-11eb-9fa7-eceab1854088.png)

2021-03-01 16:15 UTC, mi-sts commented on src/main/kotlin/homework_1/task_oop.kt
> +        val OPTIONS_RANGE: IntRange = 1..6
А, я понял как это нужно исправить

2021-03-04 20:07 UTC, mi-sts commented on src/main/kotlin/homework_1/task_oop.kt
> +            var toIndex: Int
@nbirillo до этого пробовал их инициализировать и мне выдавало такую штуку:
![image](https://user-images.githubusercontent.com/66365072/110023308-16dda180-7d3e-11eb-8790-040d1572f9fc.png)
![image](https://user-images.githubusercontent.com/66365072/110023422-3ecd0500-7d3e-11eb-9fa0-7cf0bcec2dd9.png)

2021-03-05 11:20 UTC, nbirillo requested changes

2021-03-05 11:20 UTC, nbirillo commented on src/main/kotlin/storages/PerfomedCommandStorage.kt
> +class MoveAction(val fromIndex: Int, val toIndex: Int) : Action {
А почему они не приватные?

2021-03-05 11:20 UTC, nbirillo commented on src/main/kotlin/storages/PerfomedCommandStorage.kt
> +        if (fromIndex !in 0..storage.count() || toIndex !in 0..storage.count()) {
У списка можно использовать `indices`

2021-03-05 11:20 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +    private val OPTIONS_RANGE: IntRange = 1..UserOption.values().size
Можно у класса UserOption сделать метод, который вернет этот рэндж. Причем не с 1, а возьмет просто все значения из тех, что есть, чтобы если вдруг уберется 1, то ничего не сломалось

2021-03-05 15:06 UTC, nbirillo requested changes

2021-03-05 15:06 UTC, nbirillo commented on src/main/kotlin/homework_1/task_oop.kt
> +fun main() {
![image](https://user-images.githubusercontent.com/8993915/110133516-7212a100-7ddd-11eb-8dd9-585ba82809fa.png)

+ конфликты
В остальном нормально. Если успеешь сегодня починить, то успею посмотреть

2021-03-09 15:48 UTC, nbirillo approved these changes
Зачтено

2021-03-09 15:48 UTC, merged