Homework 2. Task hard. Мищенко Станислав Алексеевич
mi-sts/spbu_kotlin_homeworks pull request #8
Opened 2021-03-14 13:48 UTC by mi-sts

2021-03-23 07:49 UTC, elena-lyulina requested changes

2021-03-23 07:49 UTC, elena-lyulina commented on build.gradle.kts
> -
а зачем ты его убираешь?

2021-03-23 07:49 UTC, elena-lyulina commented on build.gradle.kts
> +    kotlin("plugin.serialization") version "1.4.31"
разберись пожалуйста, это задача про докку или сериализацию? судя по коду -- про докку, судя по названию PR -- про сериализацию, судя по плагинам, которые ты добавил -- про все сразу

2021-03-23 07:50 UTC, elena-lyulina commented on build.gradle.kts
> +    kotlin("plugin.serialization") version "1.4.31"
если все же про сериализацию, то где, собственно, сериализация? и почему в этой ветке появилась еще не смерженная докка?

2021-03-23 08:08 UTC, elena-lyulina requested changes
Интерактивный интерейс меня порадовал, спасибо :)

2021-03-23 08:08 UTC, elena-lyulina commented on build.gradle.kts
> +    }
докка должна появляться в сосендней задаче, в этой ветке должна быть только сериализация

2021-03-23 08:08 UTC, elena-lyulina commented on src/main/kotlin/homework_1/task_oop.kt
>      private val OPTIONS_RANGE = UserOption.getOptionsIndices()
капсом пишутся только константы

2021-03-23 08:08 UTC, elena-lyulina commented on src/main/kotlin/homework_1/task_simple_1_iterative.kt
> + */
вот этого всего в этой ветке не должно быть, это другая задача

2021-03-23 08:08 UTC, elena-lyulina commented on src/main/kotlin/libraries/StringExtensions.kt
>  package libraries
такой пакет обычно называется util

2021-03-23 08:08 UTC, elena-lyulina commented on src/main/kotlin/storages/PerfomedCommandStorage.kt
> +    private val module = SerializersModule {
посмотри, пожалуйста, на [kotlin coding conventions ](https://kotlinlang.org/docs/coding-conventions.html#class-layout) и пойми, что не надо создавать переменные посередине класса послу уже объявленных методов

2021-03-23 08:08 UTC, elena-lyulina commented on src/main/kotlin/homework_1/task_oop.kt
> +const val DATA_DIR_PATH = "src/main/kotlin/homework_1/actions_data/"
используем ресурсы, не надо в src класть такие файлы, пожалуйста

2021-03-23 08:08 UTC, elena-lyulina commented on src/main/kotlin/homework_1/task_oop.kt
> +const val DATA_FILENAME = "action_data.json"
и давай не делать их константами, я уже кому-то об этом писала https://github.com/faf0be172/Kotlin_homeworks/pull/7#discussion_r599002645

в твоем случае их можно сделать приватными свойствами UserInterface

2021-03-23 08:08 UTC, elena-lyulina commented on src/main/kotlin/homework_1/task_oop.kt
> +const val DATA_DIR_PATH = "src/main/kotlin/homework_1/actions_data/"
А еще конкретно сейчас он падает при первом запуске, так как папки actions_data не существует, соответсвенно, он не может создать файл

2021-03-23 08:12 UTC, mi-sts commented on src/main/kotlin/homework_1/task_oop.kt
> +const val DATA_DIR_PATH = "src/main/kotlin/homework_1/actions_data/"
@elena-lyulina я предусмотрел этот вариант и в apply добавил createNewFile()
![image](https://user-images.githubusercontent.com/66365072/112114012-9a194700-8bc8-11eb-8579-0341d9ed59ed.png)

2021-03-23 08:14 UTC, mi-sts commented on src/main/kotlin/homework_1/task_simple_1_iterative.kt
> + */
@elena-lyulina я просто услышал, что после задачи с доккой нужно писать документацию к каждой следующей задаче и поэтому добавил её. Во второй домашке кроме докки документацию в остальных задачах нужно убрать?

2021-03-23 08:19 UTC, mi-sts commented on src/main/kotlin/homework_1/task_oop.kt
> +const val DATA_DIR_PATH = "src/main/kotlin/homework_1/actions_data/"
Я не так понял, здесь действительно падает

2021-03-23 08:41 UTC, elena-lyulina commented on src/main/kotlin/homework_1/task_simple_1_iterative.kt
> + */
аа, окей
давай тогда так оставим, у тебя она в целом хорошо написана, да и дедлайн чет уже близко
но на будущее, если надо добавить документацию к другим задачам, делай это в соответствующих ветках, а не в ветках по задаче 2.3

2021-03-26 12:09 UTC, elena-lyulina requested changes
Добавь еще, пожалуйста, этот таск в build.gradle.kts (у тебя его почему-то нет), без него нормально не собирается проект

```
tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

2021-03-26 12:09 UTC, elena-lyulina commented on src/main/kotlin/homework_1/task_oop.kt
> +    private val dataFilepath = "src/main/resources/actions_data.json"
в ресурсах должна быть та же структура пакетов, что и в месте, где ты их используешь

2021-03-26 14:31 UTC, elena-lyulina approved these changes
Класс, спасибо

2021-03-26 14:31 UTC, merged